--liquibase formatted sql

--changeset SE-Grebenyuk:02.000.00/TVR-1/load-init-data
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM tradevisor.tickers where provider = 'bybit'
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('AGLDUSDT@bybit','AGLDUSDT','AGLDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AGLD','bybit'),
	 ('ANKRUSDT@bybit','ANKRUSDT','ANKRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ANKR','bybit'),
	 ('PERPUSDT@bybit','PERPUSDT','PERPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PERP','bybit'),
	 ('WAVESUSDT@bybit','WAVESUSDT','WAVESUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WAVES','bybit'),
	 ('LUNCUSDT@bybit','LUNCUSDT','LUNCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LUNC','bybit'),
	 ('SPELLUSDT@bybit','SPELLUSDT','SPELLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SPELL','bybit'),
	 ('SHIBUSDT@bybit','SHIBUSDT','SHIBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SHIB','bybit'),
	 ('ATOMUSDT@bybit','ATOMUSDT','ATOMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ATOM','bybit'),
	 ('ALGOUSDT@bybit','ALGOUSDT','ALGOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ALGO','bybit'),
	 ('SANDUSDT@bybit','SANDUSDT','SANDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SAND','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('AVAXUSDT@bybit','AVAXUSDT','AVAXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVAX','bybit'),
	 ('WOOUSDT@bybit','WOOUSDT','WOOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WOO','bybit'),
	 ('FTTUSDT@bybit','FTTUSDT','FTTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FTT','bybit'),
	 ('GODSUSDT@bybit','GODSUSDT','GODSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GODS','bybit'),
	 ('IMXUSDT@bybit','IMXUSDT','IMXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'IMX','bybit'),
	 ('ENSUSDT@bybit','ENSUSDT','ENSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENS','bybit'),
	 ('CAKEUSDT@bybit','CAKEUSDT','CAKEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CAKE','bybit'),
	 ('STETHUSDT@bybit','STETHUSDT','STETHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STETH','bybit'),
	 ('SLPUSDT@bybit','SLPUSDT','SLPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SLP','bybit'),
	 ('C98USDT@bybit','C98USDT','C98USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'C98','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('AVAUSDT@bybit','AVAUSDT','AVAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVA','bybit'),
	 ('ONEUSDT@bybit','ONEUSDT','ONEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ONE','bybit'),
	 ('BOBAUSDT@bybit','BOBAUSDT','BOBAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BOBA','bybit'),
	 ('JASMYUSDT@bybit','JASMYUSDT','JASMYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JASMY','bybit'),
	 ('GALAUSDT@bybit','GALAUSDT','GALAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GALA','bybit'),
	 ('TRVLUSDT@bybit','TRVLUSDT','TRVLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRVL','bybit'),
	 ('WEMIXUSDT@bybit','WEMIXUSDT','WEMIXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WEMIX','bybit'),
	 ('XEMUSDT@bybit','XEMUSDT','XEMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XEM','bybit'),
	 ('BICOUSDT@bybit','BICOUSDT','BICOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BICO','bybit'),
	 ('UMAUSDT@bybit','UMAUSDT','UMAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'UMA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('NEXOUSDT@bybit','NEXOUSDT','NEXOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEXO','bybit'),
	 ('SNXUSDT@bybit','SNXUSDT','SNXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SNX','bybit'),
	 ('1INCHUSDT@bybit','1INCHUSDT','1INCHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'1INCH','bybit'),
	 ('TELUSDT@bybit','TELUSDT','TELUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TEL','bybit'),
	 ('SISUSDT@bybit','SISUSDT','SISUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SIS','bybit'),
	 ('LRCUSDT@bybit','LRCUSDT','LRCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LRC','bybit'),
	 ('LDOUSDT@bybit','LDOUSDT','LDOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LDO','bybit'),
	 ('ETHUSDC@bybit','ETHUSDC','ETHUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('BTCUSDC@bybit','BTCUSDC','BTCUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('IZIUSDT@bybit','IZIUSDT','IZIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'IZI','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('QTUMUSDT@bybit','QTUMUSDT','QTUMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'QTUM','bybit'),
	 ('ZENUSDT@bybit','ZENUSDT','ZENUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZEN','bybit'),
	 ('THETAUSDT@bybit','THETAUSDT','THETAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'THETA','bybit'),
	 ('MXUSDT@bybit','MXUSDT','MXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MX','bybit'),
	 ('DGBUSDT@bybit','DGBUSDT','DGBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DGB','bybit'),
	 ('RVNUSDT@bybit','RVNUSDT','RVNUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RVN','bybit'),
	 ('EGLDUSDT@bybit','EGLDUSDT','EGLDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'EGLD','bybit'),
	 ('RUNEUSDT@bybit','RUNEUSDT','RUNEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RUNE','bybit'),
	 ('XLMBTC@bybit','XLMBTC','XLMBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XLM','bybit'),
	 ('XLMUSDC@bybit','XLMUSDC','XLMUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XLM','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('SOLUSDC@bybit','SOLUSDC','SOLUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit'),
	 ('XRPUSDC@bybit','XRPUSDC','XRPUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XRP','bybit'),
	 ('ALGOBTC@bybit','ALGOBTC','ALGOBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ALGO','bybit'),
	 ('SOLBTC@bybit','SOLBTC','SOLBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit'),
	 ('XECUSDT@bybit','XECUSDT','XECUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XEC','bybit'),
	 ('ICXUSDT@bybit','ICXUSDT','ICXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ICX','bybit'),
	 ('XDCUSDT@bybit','XDCUSDT','XDCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XDC','bybit'),
	 ('HNTUSDT@bybit','HNTUSDT','HNTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HNT','bybit'),
	 ('ZILUSDT@bybit','ZILUSDT','ZILUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZIL','bybit'),
	 ('HBARUSDT@bybit','HBARUSDT','HBARUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HBAR','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('FLOWUSDT@bybit','FLOWUSDT','FLOWUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLOW','bybit'),
	 ('KASTAUSDT@bybit','KASTAUSDT','KASTAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KASTA','bybit'),
	 ('STXUSDT@bybit','STXUSDT','STXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STX','bybit'),
	 ('SIDUSUSDT@bybit','SIDUSUSDT','SIDUSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SIDUS','bybit'),
	 ('LOOKSUSDT@bybit','LOOKSUSDT','LOOKSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LOOKS','bybit'),
	 ('DAIUSDT@bybit','DAIUSDT','DAIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DAI','bybit'),
	 ('MVUSDT@bybit','MVUSDT','MVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MV','bybit'),
	 ('LTCUSDC@bybit','LTCUSDC','LTCUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LTC','bybit'),
	 ('LTCBTC@bybit','LTCBTC','LTCBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LTC','bybit'),
	 ('DOTBTC@bybit','DOTBTC','DOTBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('MANAUSDC@bybit','MANAUSDC','MANAUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MANA','bybit'),
	 ('SANDUSDC@bybit','SANDUSDC','SANDUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SAND','bybit'),
	 ('DOTUSDC@bybit','DOTUSDC','DOTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOT','bybit'),
	 ('LUNCUSDC@bybit','LUNCUSDC','LUNCUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LUNC','bybit'),
	 ('RSS3USDT@bybit','RSS3USDT','RSS3USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RSS3','bybit'),
	 ('GMXUSDT@bybit','GMXUSDT','GMXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GMX','bybit'),
	 ('ACHUSDT@bybit','ACHUSDT','ACHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ACH','bybit'),
	 ('JSTUSDT@bybit','JSTUSDT','JSTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JST','bybit'),
	 ('SUNUSDT@bybit','SUNUSDT','SUNUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUN','bybit'),
	 ('BTTUSDT@bybit','BTTUSDT','BTTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('TRXUSDT@bybit','TRXUSDT','TRXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRX','bybit'),
	 ('NFTUSDT@bybit','NFTUSDT','NFTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NFT','bybit'),
	 ('SCRTUSDT@bybit','SCRTUSDT','SCRTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SCRT','bybit'),
	 ('PSTAKEUSDT@bybit','PSTAKEUSDT','PSTAKEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PSTAKE','bybit'),
	 ('USTCUSDT@bybit','USTCUSDT','USTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USTC','bybit'),
	 ('BNBUSDT@bybit','BNBUSDT','BNBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BNB','bybit'),
	 ('NEARUSDT@bybit','NEARUSDT','NEARUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEAR','bybit'),
	 ('SDUSDT@bybit','SDUSDT','SDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SD','bybit'),
	 ('APEUSDT@bybit','APEUSDT','APEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APE','bybit'),
	 ('FIDAUSDT@bybit','FIDAUSDT','FIDAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FIDA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('MINAUSDT@bybit','MINAUSDT','MINAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MINA','bybit'),
	 ('SCUSDT@bybit','SCUSDT','SCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SC','bybit'),
	 ('RACAUSDT@bybit','RACAUSDT','RACAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RACA','bybit'),
	 ('GLMRUSDT@bybit','GLMRUSDT','GLMRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GLMR','bybit'),
	 ('MOVRUSDT@bybit','MOVRUSDT','MOVRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MOVR','bybit'),
	 ('ETHDAI@bybit','ETHDAI','ETHDAI@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('BTCDAI@bybit','BTCDAI','BTCDAI@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('WBTCUSDT@bybit','WBTCUSDT','WBTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WBTC','bybit'),
	 ('XAVAUSDT@bybit','XAVAUSDT','XAVAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XAVA','bybit'),
	 ('GMTUSDT@bybit','GMTUSDT','GMTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GMT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('CELOUSDT@bybit','CELOUSDT','CELOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CELO','bybit'),
	 ('SFUNDUSDT@bybit','SFUNDUSDT','SFUNDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SFUND','bybit'),
	 ('APEXUSDT@bybit','APEXUSDT','APEXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APEX','bybit'),
	 ('CTCUSDT@bybit','CTCUSDT','CTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CTC','bybit'),
	 ('FITFIUSDT@bybit','FITFIUSDT','FITFIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FITFI','bybit'),
	 ('USDDUSDT@bybit','USDDUSDT','USDDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDD','bybit'),
	 ('OPUSDT@bybit','OPUSDT','OPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OP','bybit'),
	 ('LUNAUSDT@bybit','LUNAUSDT','LUNAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LUNA','bybit'),
	 ('VINUUSDT@bybit','VINUUSDT','VINUUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VINU','bybit'),
	 ('BELUSDT@bybit','BELUSDT','BELUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BEL','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('FORTUSDT@bybit','FORTUSDT','FORTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FORT','bybit'),
	 ('DOGEUSDC@bybit','DOGEUSDC','DOGEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGE','bybit'),
	 ('FLOKIUSDT@bybit','FLOKIUSDT','FLOKIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLOKI','bybit'),
	 ('BABYDOGEUSDT@bybit','BABYDOGEUSDT','BABYDOGEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BABYDOGE','bybit'),
	 ('WAXPUSDT@bybit','WAXPUSDT','WAXPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WAXP','bybit'),
	 ('ARUSDT@bybit','ARUSDT','ARUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AR','bybit'),
	 ('ROSEUSDT@bybit','ROSEUSDT','ROSEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ROSE','bybit'),
	 ('PSGUSDT@bybit','PSGUSDT','PSGUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PSG','bybit'),
	 ('JUVUSDT@bybit','JUVUSDT','JUVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JUV','bybit'),
	 ('INTERUSDT@bybit','INTERUSDT','INTERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'INTER','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('AFCUSDT@bybit','AFCUSDT','AFCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AFC','bybit'),
	 ('CITYUSDT@bybit','CITYUSDT','CITYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CITY','bybit'),
	 ('SOLOUSDT@bybit','SOLOUSDT','SOLOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOLO','bybit'),
	 ('WBTCBTC@bybit','WBTCBTC','WBTCBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WBTC','bybit'),
	 ('AVAXUSDC@bybit','AVAXUSDC','AVAXUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVAX','bybit'),
	 ('ADAUSDC@bybit','ADAUSDC','ADAUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ADA','bybit'),
	 ('OPUSDC@bybit','OPUSDC','OPUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OP','bybit'),
	 ('APEXUSDC@bybit','APEXUSDC','APEXUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APEX','bybit'),
	 ('TRXUSDC@bybit','TRXUSDC','TRXUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRX','bybit'),
	 ('ICPUSDC@bybit','ICPUSDC','ICPUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ICP','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('LINKUSDC@bybit','LINKUSDC','LINKUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LINK','bybit'),
	 ('GMTUSDC@bybit','GMTUSDC','GMTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GMT','bybit'),
	 ('CHZUSDC@bybit','CHZUSDC','CHZUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CHZ','bybit'),
	 ('SHIBUSDC@bybit','SHIBUSDC','SHIBUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SHIB','bybit'),
	 ('LDOUSDC@bybit','LDOUSDC','LDOUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LDO','bybit'),
	 ('APEUSDC@bybit','APEUSDC','APEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APE','bybit'),
	 ('FILUSDC@bybit','FILUSDC','FILUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FIL','bybit'),
	 ('SWEATUSDT@bybit','SWEATUSDT','SWEATUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SWEAT','bybit'),
	 ('ETHWUSDT@bybit','ETHWUSDT','ETHWUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETHW','bybit'),
	 ('INJUSDT@bybit','INJUSDT','INJUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'INJ','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('MPLXUSDT@bybit','MPLXUSDT','MPLXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MPLX','bybit'),
	 ('APTUSDT@bybit','APTUSDT','APTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APT','bybit'),
	 ('APTUSDC@bybit','APTUSDC','APTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APT','bybit'),
	 ('USDTEUR@bybit','USDTEUR','USDTEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDT','bybit'),
	 ('MCRTUSDT@bybit','MCRTUSDT','MCRTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MCRT','bybit'),
	 ('MASKUSDT@bybit','MASKUSDT','MASKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MASK','bybit'),
	 ('HFTUSDC@bybit','HFTUSDC','HFTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HFT','bybit'),
	 ('HFTUSDT@bybit','HFTUSDT','HFTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HFT','bybit'),
	 ('PEOPLEUSDT@bybit','PEOPLEUSDT','PEOPLEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PEOPLE','bybit'),
	 ('TWTUSDT@bybit','TWTUSDT','TWTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TWT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ORTUSDT@bybit','ORTUSDT','ORTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ORT','bybit'),
	 ('HOOKUSDT@bybit','HOOKUSDT','HOOKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HOOK','bybit'),
	 ('OASUSDT@bybit','OASUSDT','OASUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OAS','bybit'),
	 ('MAGICUSDT@bybit','MAGICUSDT','MAGICUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MAGIC','bybit'),
	 ('MEEUSDT@bybit','MEEUSDT','MEEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MEE','bybit'),
	 ('TONUSDT@bybit','TONUSDT','TONUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TON','bybit'),
	 ('BONKUSDT@bybit','BONKUSDT','BONKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BONK','bybit'),
	 ('FLRUSDT@bybit','FLRUSDT','FLRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLR','bybit'),
	 ('TIMEUSDT@bybit','TIMEUSDT','TIMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TIME','bybit'),
	 ('RPLUSDT@bybit','RPLUSDT','RPLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RPL','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('SSVUSDT@bybit','SSVUSDT','SSVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SSV','bybit'),
	 ('FXSUSDT@bybit','FXSUSDT','FXSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FXS','bybit'),
	 ('COREUSDT@bybit','COREUSDT','COREUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CORE','bybit'),
	 ('RDNTUSDT@bybit','RDNTUSDT','RDNTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RDNT','bybit'),
	 ('BLURUSDT@bybit','BLURUSDT','BLURUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BLUR','bybit'),
	 ('MDAOUSDT@bybit','MDAOUSDT','MDAOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MDAO','bybit'),
	 ('ACSUSDT@bybit','ACSUSDT','ACSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ACS','bybit'),
	 ('PRIMEUSDT@bybit','PRIMEUSDT','PRIMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PRIME','bybit'),
	 ('VRAUSDT@bybit','VRAUSDT','VRAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VRA','bybit'),
	 ('IDUSDT@bybit','IDUSDT','IDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ID','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ARBUSDC@bybit','ARBUSDC','ARBUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ARB','bybit'),
	 ('ARBUSDT@bybit','ARBUSDT','ARBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ARB','bybit'),
	 ('XCADUSDT@bybit','XCADUSDT','XCADUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XCAD','bybit'),
	 ('MBXUSDT@bybit','MBXUSDT','MBXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MBX','bybit'),
	 ('AXLUSDT@bybit','AXLUSDT','AXLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AXL','bybit'),
	 ('CGPTUSDT@bybit','CGPTUSDT','CGPTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CGPT','bybit'),
	 ('AGIUSDT@bybit','AGIUSDT','AGIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AGI','bybit'),
	 ('SUIUSDT@bybit','SUIUSDT','SUIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUI','bybit'),
	 ('SUIUSDC@bybit','SUIUSDC','SUIUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUI','bybit'),
	 ('MVLUSDT@bybit','MVLUSDT','MVLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MVL','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PEPEUSDT@bybit','PEPEUSDT','PEPEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PEPE','bybit'),
	 ('LADYSUSDT@bybit','LADYSUSDT','LADYSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LADYS','bybit'),
	 ('LMWRUSDT@bybit','LMWRUSDT','LMWRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LMWR','bybit'),
	 ('TURBOSUSDT@bybit','TURBOSUSDT','TURBOSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TURBOS','bybit'),
	 ('VELOUSDT@bybit','VELOUSDT','VELOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VELO','bybit'),
	 ('PENDLEUSDT@bybit','PENDLEUSDT','PENDLEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PENDLE','bybit'),
	 ('NYMUSDT@bybit','NYMUSDT','NYMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NYM','bybit'),
	 ('MNTUSDT@bybit','MNTUSDT','MNTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MNT','bybit'),
	 ('MNTUSDC@bybit','MNTUSDC','MNTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MNT','bybit'),
	 ('MNTBTC@bybit','MNTBTC','MNTBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MNT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ARKMUSDT@bybit','ARKMUSDT','ARKMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ARKM','bybit'),
	 ('NEONUSDT@bybit','NEONUSDT','NEONUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEON','bybit'),
	 ('WLDUSDC@bybit','WLDUSDC','WLDUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WLD','bybit'),
	 ('WLDUSDT@bybit','WLDUSDT','WLDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WLD','bybit'),
	 ('SEIUSDT@bybit','SEIUSDT','SEIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SEI','bybit'),
	 ('CYBERUSDT@bybit','CYBERUSDT','CYBERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CYBER','bybit'),
	 ('ORDIUSDT@bybit','ORDIUSDT','ORDIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ORDI','bybit'),
	 ('KAVAUSDT@bybit','KAVAUSDT','KAVAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KAVA','bybit'),
	 ('PYUSDUSDT@bybit','PYUSDUSDT','PYUSDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PYUSD','bybit'),
	 ('SOLEUR@bybit','SOLEUR','SOLEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('USDCEUR@bybit','USDCEUR','USDCEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDC','bybit'),
	 ('ADAEUR@bybit','ADAEUR','ADAEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ADA','bybit'),
	 ('DOGEEUR@bybit','DOGEEUR','DOGEEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGE','bybit'),
	 ('LTCEUR@bybit','LTCEUR','LTCEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LTC','bybit'),
	 ('XRPEUR@bybit','XRPEUR','XRPEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XRP','bybit'),
	 ('ETHEUR@bybit','ETHEUR','ETHEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('BTCEUR@bybit','BTCEUR','BTCEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('KASUSDT@bybit','KASUSDT','KASUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KAS','bybit'),
	 ('FETUSDT@bybit','FETUSDT','FETUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FET','bybit'),
	 ('ZTXUSDT@bybit','ZTXUSDT','ZTXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZTX','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('JEFFUSDT@bybit','JEFFUSDT','JEFFUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JEFF','bybit'),
	 ('TUSDUSDT@bybit','TUSDUSDT','TUSDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TUSD','bybit'),
	 ('BEAMUSDT@bybit','BEAMUSDT','BEAMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BEAM','bybit'),
	 ('POLUSDT@bybit','POLUSDT','POLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'POL','bybit'),
	 ('TIAUSDT@bybit','TIAUSDT','TIAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TIA','bybit'),
	 ('TOKENUSDT@bybit','TOKENUSDT','TOKENUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TOKEN','bybit'),
	 ('MEMEUSDT@bybit','MEMEUSDT','MEMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MEME','bybit'),
	 ('SHRAPUSDT@bybit','SHRAPUSDT','SHRAPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SHRAP','bybit'),
	 ('FLIPUSDT@bybit','FLIPUSDT','FLIPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLIP','bybit'),
	 ('ROOTUSDT@bybit','ROOTUSDT','ROOTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ROOT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PYTHUSDT@bybit','PYTHUSDT','PYTHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PYTH','bybit'),
	 ('KUBUSDT@bybit','KUBUSDT','KUBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KUB','bybit'),
	 ('KCSUSDT@bybit','KCSUSDT','KCSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KCS','bybit'),
	 ('VANRYUSDT@bybit','VANRYUSDT','VANRYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VANRY','bybit'),
	 ('INSPUSDT@bybit','INSPUSDT','INSPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'INSP','bybit'),
	 ('JTOUSDT@bybit','JTOUSDT','JTOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JTO','bybit'),
	 ('METHUSDT@bybit','METHUSDT','METHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'METH','bybit'),
	 ('METHETH@bybit','METHETH','METHETH@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'METH','bybit'),
	 ('CBKUSDT@bybit','CBKUSDT','CBKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CBK','bybit'),
	 ('ZIGUSDT@bybit','ZIGUSDT','ZIGUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZIG','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('TRCUSDT@bybit','TRCUSDT','TRCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRC','bybit'),
	 ('SEIUSDC@bybit','SEIUSDC','SEIUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SEI','bybit'),
	 ('MYRIAUSDT@bybit','MYRIAUSDT','MYRIAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MYRIA','bybit'),
	 ('MBOXUSDT@bybit','MBOXUSDT','MBOXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MBOX','bybit'),
	 ('ARTYUSDT@bybit','ARTYUSDT','ARTYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ARTY','bybit'),
	 ('COQUSDT@bybit','COQUSDT','COQUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'COQ','bybit'),
	 ('AIOZUSDT@bybit','AIOZUSDT','AIOZUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AIOZ','bybit'),
	 ('VICUSDT@bybit','VICUSDT','VICUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VIC','bybit'),
	 ('RATSUSDT@bybit','RATSUSDT','RATSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RATS','bybit'),
	 ('SATSUSDT@bybit','SATSUSDT','SATSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SATS','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PORT3USDT@bybit','PORT3USDT','PORT3USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PORT3','bybit'),
	 ('XAIUSDT@bybit','XAIUSDT','XAIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XAI','bybit'),
	 ('ONDOUSDT@bybit','ONDOUSDT','ONDOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ONDO','bybit'),
	 ('SQRUSDT@bybit','SQRUSDT','SQRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SQR','bybit'),
	 ('SAROSUSDT@bybit','SAROSUSDT','SAROSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SAROS','bybit'),
	 ('USDYUSDT@bybit','USDYUSDT','USDYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDY','bybit'),
	 ('MANTAUSDT@bybit','MANTAUSDT','MANTAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MANTA','bybit'),
	 ('MYROUSDT@bybit','MYROUSDT','MYROUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MYRO','bybit'),
	 ('GTAIUSDT@bybit','GTAIUSDT','GTAIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GTAI','bybit'),
	 ('DMAILUSDT@bybit','DMAILUSDT','DMAILUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DMAIL','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('DYMUSDT@bybit','DYMUSDT','DYMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DYM','bybit'),
	 ('ZETAUSDT@bybit','ZETAUSDT','ZETAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZETA','bybit'),
	 ('JUPUSDT@bybit','JUPUSDT','JUPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JUP','bybit'),
	 ('MAVIAUSDT@bybit','MAVIAUSDT','MAVIAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MAVIA','bybit'),
	 ('PURSEUSDT@bybit','PURSEUSDT','PURSEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PURSE','bybit'),
	 ('ALTUSDT@bybit','ALTUSDT','ALTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ALT','bybit'),
	 ('HTXUSDT@bybit','HTXUSDT','HTXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HTX','bybit'),
	 ('CSPRUSDT@bybit','CSPRUSDT','CSPRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CSPR','bybit'),
	 ('STRKUSDC@bybit','STRKUSDC','STRKUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STRK','bybit'),
	 ('STRKUSDT@bybit','STRKUSDT','STRKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STRK','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('CPOOLUSDT@bybit','CPOOLUSDT','CPOOLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CPOOL','bybit'),
	 ('QORPOUSDT@bybit','QORPOUSDT','QORPOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'QORPO','bybit'),
	 ('PORTALUSDT@bybit','PORTALUSDT','PORTALUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PORTAL','bybit'),
	 ('SCAUSDT@bybit','SCAUSDT','SCAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SCA','bybit'),
	 ('AEVOUSDT@bybit','AEVOUSDT','AEVOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AEVO','bybit'),
	 ('NIBIUSDT@bybit','NIBIUSDT','NIBIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NIBI','bybit'),
	 ('BOMEUSDT@bybit','BOMEUSDT','BOMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BOME','bybit'),
	 ('VENOMUSDT@bybit','VENOMUSDT','VENOMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VENOM','bybit'),
	 ('ZKJUSDT@bybit','ZKJUSDT','ZKJUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZKJ','bybit'),
	 ('ETHFIUSDT@bybit','ETHFIUSDT','ETHFIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETHFI','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('WEETHETH@bybit','WEETHETH','WEETHETH@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WEETH','bybit'),
	 ('NAKAUSDT@bybit','NAKAUSDT','NAKAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NAKA','bybit'),
	 ('WENUSDT@bybit','WENUSDT','WENUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WEN','bybit'),
	 ('DEGENUSDT@bybit','DEGENUSDT','DEGENUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DEGEN','bybit'),
	 ('ENAUSDT@bybit','ENAUSDT','ENAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENA','bybit'),
	 ('USDEUSDT@bybit','USDEUSDT','USDEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDE','bybit'),
	 ('WUSDT@bybit','WUSDT','WUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'W','bybit'),
	 ('G3USDT@bybit','G3USDT','G3USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'G3','bybit'),
	 ('ESEUSDT@bybit','ESEUSDT','ESEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ESE','bybit'),
	 ('TNSRUSDT@bybit','TNSRUSDT','TNSRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TNSR','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('MASAUSDT@bybit','MASAUSDT','MASAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MASA','bybit'),
	 ('FOXYUSDT@bybit','FOXYUSDT','FOXYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FOXY','bybit'),
	 ('PRCLUSDT@bybit','PRCLUSDT','PRCLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PRCL','bybit'),
	 ('BRETTUSDT@bybit','BRETTUSDT','BRETTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BRETT','bybit'),
	 ('MEWUSDT@bybit','MEWUSDT','MEWUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MEW','bybit'),
	 ('MERLUSDT@bybit','MERLUSDT','MERLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MERL','bybit'),
	 ('LLUSDT@bybit','LLUSDT','LLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LL','bybit'),
	 ('SAFEUSDT@bybit','SAFEUSDT','SAFEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SAFE','bybit'),
	 ('WIFUSDT@bybit','WIFUSDT','WIFUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WIF','bybit'),
	 ('SVLUSDT@bybit','SVLUSDT','SVLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SVL','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('KMNOUSDT@bybit','KMNOUSDT','KMNOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KMNO','bybit'),
	 ('ZENTUSDT@bybit','ZENTUSDT','ZENTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZENT','bybit'),
	 ('TAIUSDT@bybit','TAIUSDT','TAIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TAI','bybit'),
	 ('MODEUSDT@bybit','MODEUSDT','MODEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MODE','bybit'),
	 ('SPECUSDT@bybit','SPECUSDT','SPECUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SPEC','bybit'),
	 ('PONKEUSDT@bybit','PONKEUSDT','PONKEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PONKE','bybit'),
	 ('BBUSDT@bybit','BBUSDT','BBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BB','bybit'),
	 ('CTAUSDT@bybit','CTAUSDT','CTAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CTA','bybit'),
	 ('NOTUSDT@bybit','NOTUSDT','NOTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NOT','bybit'),
	 ('DRIFTUSDT@bybit','DRIFTUSDT','DRIFTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DRIFT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('SQDUSDT@bybit','SQDUSDT','SQDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SQD','bybit'),
	 ('USDEUSDC@bybit','USDEUSDC','USDEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDE','bybit'),
	 ('SOLUSDE@bybit','SOLUSDE','SOLUSDE@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit'),
	 ('ETHUSDE@bybit','ETHUSDE','ETHUSDE@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('BTCUSDE@bybit','BTCUSDE','BTCUSDE@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('MONPROUSDT@bybit','MONPROUSDT','MONPROUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MONPRO','bybit'),
	 ('MOGUSDT@bybit','MOGUSDT','MOGUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MOG','bybit'),
	 ('TAIKOUSDT@bybit','TAIKOUSDT','TAIKOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TAIKO','bybit'),
	 ('ULTIUSDT@bybit','ULTIUSDT','ULTIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ULTI','bybit'),
	 ('AURORAUSDT@bybit','AURORAUSDT','AURORAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AURORA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('IOUSDT@bybit','IOUSDT','IOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'IO','bybit'),
	 ('ATHUSDT@bybit','ATHUSDT','ATHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ATH','bybit'),
	 ('COOKIEUSDT@bybit','COOKIEUSDT','COOKIEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'COOKIE','bybit'),
	 ('PIRATEUSDT@bybit','PIRATEUSDT','PIRATEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PIRATE','bybit'),
	 ('ZKUSDC@bybit','ZKUSDC','ZKUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZK','bybit'),
	 ('ZKUSDT@bybit','ZKUSDT','ZKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZK','bybit'),
	 ('POPCATUSDT@bybit','POPCATUSDT','POPCATUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'POPCAT','bybit'),
	 ('ZROUSDC@bybit','ZROUSDC','ZROUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZRO','bybit'),
	 ('ZROUSDT@bybit','ZROUSDT','ZROUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZRO','bybit'),
	 ('NRNUSDT@bybit','NRNUSDT','NRNUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NRN','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ZEXUSDT@bybit','ZEXUSDT','ZEXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZEX','bybit'),
	 ('BLASTUSDT@bybit','BLASTUSDT','BLASTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BLAST','bybit'),
	 ('BTCBRL@bybit','BTCBRL','BTCBRL@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('ETHBRL@bybit','ETHBRL','ETHBRL@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('SOLBRL@bybit','SOLBRL','SOLBRL@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit'),
	 ('USDTBRL@bybit','USDTBRL','USDTBRL@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDT','bybit'),
	 ('USDCBRL@bybit','USDCBRL','USDCBRL@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDC','bybit'),
	 ('NEAREUR@bybit','NEAREUR','NEAREUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEAR','bybit'),
	 ('SHIBEUR@bybit','SHIBEUR','SHIBEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SHIB','bybit'),
	 ('WIFEUR@bybit','WIFEUR','WIFEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WIF','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PEPEEUR@bybit','PEPEEUR','PEPEEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PEPE','bybit'),
	 ('AVAXEUR@bybit','AVAXEUR','AVAXEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVAX','bybit'),
	 ('ONDOEUR@bybit','ONDOEUR','ONDOEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ONDO','bybit'),
	 ('STETHEUR@bybit','STETHEUR','STETHEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STETH','bybit'),
	 ('WLDEUR@bybit','WLDEUR','WLDEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WLD','bybit'),
	 ('ENAEUR@bybit','ENAEUR','ENAEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENA','bybit'),
	 ('TONEUR@bybit','TONEUR','TONEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TON','bybit'),
	 ('LINKEUR@bybit','LINKEUR','LINKEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LINK','bybit'),
	 ('MOCAUSDT@bybit','MOCAUSDT','MOCAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MOCA','bybit'),
	 ('UXLINKUSDT@bybit','UXLINKUSDT','UXLINKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'UXLINK','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('A8USDT@bybit','A8USDT','A8USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'A8','bybit'),
	 ('CLOUDUSDT@bybit','CLOUDUSDT','CLOUDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CLOUD','bybit'),
	 ('ZKLUSDT@bybit','ZKLUSDT','ZKLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZKL','bybit'),
	 ('AVAILUSDT@bybit','AVAILUSDT','AVAILUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVAIL','bybit'),
	 ('L3USDT@bybit','L3USDT','L3USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'L3','bybit'),
	 ('RENDERUSDT@bybit','RENDERUSDT','RENDERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RENDER','bybit'),
	 ('GUSDT@bybit','GUSDT','GUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'G','bybit'),
	 ('TONUSDC@bybit','TONUSDC','TONUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TON','bybit'),
	 ('WIFUSDC@bybit','WIFUSDC','WIFUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WIF','bybit'),
	 ('PEPEUSDC@bybit','PEPEUSDC','PEPEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PEPE','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('DOGSUSDT@bybit','DOGSUSDT','DOGSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGS','bybit'),
	 ('NOTUSDC@bybit','NOTUSDC','NOTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NOT','bybit'),
	 ('BNBUSDC@bybit','BNBUSDC','BNBUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BNB','bybit'),
	 ('BONKUSDC@bybit','BONKUSDC','BONKUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BONK','bybit'),
	 ('DOGSUSDC@bybit','DOGSUSDC','DOGSUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGS','bybit'),
	 ('DOGSEUR@bybit','DOGSEUR','DOGSEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGS','bybit'),
	 ('USDTPLN@bybit','USDTPLN','USDTPLN@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDT','bybit'),
	 ('ETHPLN@bybit','ETHPLN','ETHPLN@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('BTCPLN@bybit','BTCPLN','BTCPLN@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('FLOKIUSDC@bybit','FLOKIUSDC','FLOKIUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLOKI','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('BCHUSDC@bybit','BCHUSDC','BCHUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BCH','bybit'),
	 ('NEARUSDC@bybit','NEARUSDC','NEARUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEAR','bybit'),
	 ('ORDERUSDT@bybit','ORDERUSDT','ORDERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ORDER','bybit'),
	 ('ETHTRY@bybit','ETHTRY','ETHTRY@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('BTCTRY@bybit','BTCTRY','BTCTRY@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('USDTTRY@bybit','USDTTRY','USDTTRY@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDT','bybit'),
	 ('MEWUSDC@bybit','MEWUSDC','MEWUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MEW','bybit'),
	 ('KASUSDC@bybit','KASUSDC','KASUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KAS','bybit'),
	 ('ONDOUSDC@bybit','ONDOUSDC','ONDOUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ONDO','bybit'),
	 ('JASMYUSDC@bybit','JASMYUSDC','JASMYUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JASMY','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ATOMUSDC@bybit','ATOMUSDC','ATOMUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ATOM','bybit'),
	 ('FETUSDC@bybit','FETUSDC','FETUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FET','bybit'),
	 ('UNIUSDC@bybit','UNIUSDC','UNIUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'UNI','bybit'),
	 ('BRETTUSDC@bybit','BRETTUSDC','BRETTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BRETT','bybit'),
	 ('TIAUSDC@bybit','TIAUSDC','TIAUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TIA','bybit'),
	 ('INJUSDC@bybit','INJUSDC','INJUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'INJ','bybit'),
	 ('SUNDOGUSDT@bybit','SUNDOGUSDT','SUNDOGUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUNDOG','bybit'),
	 ('CATIUSDT@bybit','CATIUSDT','CATIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CATI','bybit'),
	 ('HMSTRUSDT@bybit','HMSTRUSDT','HMSTRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HMSTR','bybit'),
	 ('CATIUSDC@bybit','CATIUSDC','CATIUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CATI','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('CATIEUR@bybit','CATIEUR','CATIEUR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CATI','bybit'),
	 ('HMSTRUSDC@bybit','HMSTRUSDC','HMSTRUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HMSTR','bybit'),
	 ('EIGENUSDT@bybit','EIGENUSDT','EIGENUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'EIGEN','bybit'),
	 ('NAVXUSDT@bybit','NAVXUSDT','NAVXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NAVX','bybit'),
	 ('BBSOLUSDC@bybit','BBSOLUSDC','BBSOLUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BBSOL','bybit'),
	 ('BBSOLUSDT@bybit','BBSOLUSDT','BBSOLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BBSOL','bybit'),
	 ('CARVUSDT@bybit','CARVUSDT','CARVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CARV','bybit'),
	 ('DEEPUSDT@bybit','DEEPUSDT','DEEPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DEEP','bybit'),
	 ('PUFFERUSDT@bybit','PUFFERUSDT','PUFFERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PUFFER','bybit'),
	 ('DBRUSDT@bybit','DBRUSDT','DBRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DBR','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PUFFUSDT@bybit','PUFFUSDT','PUFFUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PUFF','bybit'),
	 ('SCRUSDT@bybit','SCRUSDT','SCRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SCR','bybit'),
	 ('XUSDT@bybit','XUSDT','XUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'X','bybit'),
	 ('COOKUSDT@bybit','COOKUSDT','COOKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'COOK','bybit'),
	 ('GRASSUSDT@bybit','GRASSUSDT','GRASSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GRASS','bybit'),
	 ('KAIAUSDT@bybit','KAIAUSDT','KAIAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KAIA','bybit'),
	 ('SWELLUSDT@bybit','SWELLUSDT','SWELLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SWELL','bybit'),
	 ('SWELLUSDC@bybit','SWELLUSDC','SWELLUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SWELL','bybit'),
	 ('NSUSDT@bybit','NSUSDT','NSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NS','bybit'),
	 ('GOATUSDT@bybit','GOATUSDT','GOATUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GOAT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('CMETHUSDT@bybit','CMETHUSDT','CMETHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CMETH','bybit'),
	 ('MORPHOUSDT@bybit','MORPHOUSDT','MORPHOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MORPHO','bybit'),
	 ('NEIROCTOUSDT@bybit','NEIROCTOUSDT','NEIROCTOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEIROCTO','bybit'),
	 ('BANUSDT@bybit','BANUSDT','BANUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BAN','bybit'),
	 ('OLUSDT@bybit','OLUSDT','OLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OL','bybit'),
	 ('VIRTUALUSDT@bybit','VIRTUALUSDT','VIRTUALUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VIRTUAL','bybit'),
	 ('MAJORUSDT@bybit','MAJORUSDT','MAJORUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MAJOR','bybit'),
	 ('MEMEFIUSDT@bybit','MEMEFIUSDT','MEMEFIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MEMEFI','bybit'),
	 ('PNUTUSDT@bybit','PNUTUSDT','PNUTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PNUT','bybit'),
	 ('SPXUSDT@bybit','SPXUSDT','SPXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SPX','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ZRCUSDT@bybit','ZRCUSDT','ZRCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZRC','bybit'),
	 ('CHILLGUYUSDT@bybit','CHILLGUYUSDT','CHILLGUYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CHILLGUY','bybit'),
	 ('SUPRAUSDT@bybit','SUPRAUSDT','SUPRAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUPRA','bybit'),
	 ('PAALUSDT@bybit','PAALUSDT','PAALUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PAAL','bybit'),
	 ('FUSDT@bybit','FUSDT','FUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'F','bybit'),
	 ('HPOS10IUSDT@bybit','HPOS10IUSDT','HPOS10IUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HPOS10I','bybit'),
	 ('BBSOLSOL@bybit','BBSOLSOL','BBSOLSOL@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BBSOL','bybit'),
	 ('XIONUSDT@bybit','XIONUSDT','XIONUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XION','bybit'),
	 ('MOVEUSDT@bybit','MOVEUSDT','MOVEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MOVE','bybit'),
	 ('MEUSDT@bybit','MEUSDT','MEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ME','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ZEREBROUSDT@bybit','ZEREBROUSDT','ZEREBROUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZEREBRO','bybit'),
	 ('SENDUSDT@bybit','SENDUSDT','SENDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SEND','bybit'),
	 ('AEROUSDT@bybit','AEROUSDT','AEROUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AERO','bybit'),
	 ('STREAMUSDT@bybit','STREAMUSDT','STREAMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STREAM','bybit'),
	 ('VANAUSDT@bybit','VANAUSDT','VANAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VANA','bybit'),
	 ('LUNAIUSDT@bybit','LUNAIUSDT','LUNAIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LUNAI','bybit'),
	 ('PENGUUSDT@bybit','PENGUUSDT','PENGUUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PENGU','bybit'),
	 ('FLUIDUSDT@bybit','FLUIDUSDT','FLUIDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLUID','bybit'),
	 ('FUELUSDT@bybit','FUELUSDT','FUELUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FUEL','bybit'),
	 ('ODOSUSDT@bybit','ODOSUSDT','ODOSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ODOS','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ALCHUSDT@bybit','ALCHUSDT','ALCHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ALCH','bybit'),
	 ('FLOCKUSDT@bybit','FLOCKUSDT','FLOCKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FLOCK','bybit'),
	 ('SONICUSDT@bybit','SONICUSDT','SONICUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SONIC','bybit'),
	 ('SERAPHUSDT@bybit','SERAPHUSDT','SERAPHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SERAPH','bybit'),
	 ('LAVAUSDT@bybit','LAVAUSDT','LAVAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LAVA','bybit'),
	 ('XTERUSDT@bybit','XTERUSDT','XTERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XTER','bybit'),
	 ('AI16ZUSDT@bybit','AI16ZUSDT','AI16ZUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AI16Z','bybit'),
	 ('GAMEUSDT@bybit','GAMEUSDT','GAMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GAME','bybit'),
	 ('AIXBTUSDT@bybit','AIXBTUSDT','AIXBTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AIXBT','bybit'),
	 ('JUSDT@bybit','JUSDT','JUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'J','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('SUSDT@bybit','SUSDT','SUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'S','bybit'),
	 ('BMTUSDT@bybit','BMTUSDT','BMTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BMT','bybit'),
	 ('TOSHIUSDT@bybit','TOSHIUSDT','TOSHIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TOSHI','bybit'),
	 ('GPSUSDT@bybit','GPSUSDT','GPSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GPS','bybit'),
	 ('SOLVUSDT@bybit','SOLVUSDT','SOLVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOLV','bybit'),
	 ('OBTUSDT@bybit','OBTUSDT','OBTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OBT','bybit'),
	 ('SOSOUSDT@bybit','SOSOUSDT','SOSOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOSO','bybit'),
	 ('TRUMPUSDT@bybit','TRUMPUSDT','TRUMPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRUMP','bybit'),
	 ('TRUMPUSDC@bybit','TRUMPUSDC','TRUMPUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRUMP','bybit'),
	 ('PLUMEUSDT@bybit','PLUMEUSDT','PLUMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PLUME','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ANIMEUSDT@bybit','ANIMEUSDT','ANIMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ANIME','bybit'),
	 ('LAYERUSDT@bybit','LAYERUSDT','LAYERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LAYER','bybit'),
	 ('PINEYEUSDT@bybit','PINEYEUSDT','PINEYEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PINEYE','bybit'),
	 ('BERAUSDT@bybit','BERAUSDT','BERAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BERA','bybit'),
	 ('AVLUSDT@bybit','AVLUSDT','AVLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVL','bybit'),
	 ('B3USDT@bybit','B3USDT','B3USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'B3','bybit'),
	 ('DIAMUSDT@bybit','DIAMUSDT','DIAMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DIAM','bybit'),
	 ('IPUSDT@bybit','IPUSDT','IPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'IP','bybit'),
	 ('OMUSDT@bybit','OMUSDT','OMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OM','bybit'),
	 ('USDTBUSDT@bybit','USDTBUSDT','USDTBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDTB','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ROAMUSDT@bybit','ROAMUSDT','ROAMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ROAM','bybit'),
	 ('ELXUSDT@bybit','ELXUSDT','ELXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ELX','bybit'),
	 ('REDUSDT@bybit','REDUSDT','REDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RED','bybit'),
	 ('PELLUSDT@bybit','PELLUSDT','PELLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PELL','bybit'),
	 ('BRUSDT@bybit','BRUSDT','BRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BR','bybit'),
	 ('VVVUSDT@bybit','VVVUSDT','VVVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VVV','bybit'),
	 ('USDQUSDT@bybit','USDQUSDT','USDQUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDQ','bybit'),
	 ('BTCUSDQ@bybit','BTCUSDQ','BTCUSDQ@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('WALUSDT@bybit','WALUSDT','WALUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WAL','bybit'),
	 ('AMIUSDT@bybit','AMIUSDT','AMIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AMI','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PARTIUSDT@bybit','PARTIUSDT','PARTIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PARTI','bybit'),
	 ('CORNUSDT@bybit','CORNUSDT','CORNUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CORN','bybit'),
	 ('KILOUSDT@bybit','KILOUSDT','KILOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KILO','bybit'),
	 ('PUMPBTCUSDT@bybit','PUMPBTCUSDT','PUMPBTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PUMPBTC','bybit'),
	 ('USDRUSDT@bybit','USDRUSDT','USDRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDR','bybit'),
	 ('BTCUSDR@bybit','BTCUSDR','BTCUSDR@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('FHEUSDT@bybit','FHEUSDT','FHEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FHE','bybit'),
	 ('BABY1USDT@bybit','BABY1USDT','BABY1USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BABY1','bybit'),
	 ('XAUTUSDT@bybit','XAUTUSDT','XAUTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XAUT','bybit'),
	 ('VETUSDT@bybit','VETUSDT','VETUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VET','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('VTHOUSDT@bybit','VTHOUSDT','VTHOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VTHO','bybit'),
	 ('WCTUSDT@bybit','WCTUSDT','WCTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WCT','bybit'),
	 ('EPTUSDT@bybit','EPTUSDT','EPTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'EPT','bybit'),
	 ('DOLOUSDT@bybit','DOLOUSDT','DOLOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOLO','bybit'),
	 ('HYPERUSDT@bybit','HYPERUSDT','HYPERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HYPER','bybit'),
	 ('ZORAUSDT@bybit','ZORAUSDT','ZORAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZORA','bybit'),
	 ('INITUSDT@bybit','INITUSDT','INITUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'INIT','bybit'),
	 ('SIGNUSDT@bybit','SIGNUSDT','SIGNUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SIGN','bybit'),
	 ('HAEDALUSDT@bybit','HAEDALUSDT','HAEDALUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HAEDAL','bybit'),
	 ('MILKUSDT@bybit','MILKUSDT','MILKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MILK','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('OBOLUSDT@bybit','OBOLUSDT','OBOLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'OBOL','bybit'),
	 ('SXTUSDT@bybit','SXTUSDT','SXTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SXT','bybit'),
	 ('DOODUSDT@bybit','DOODUSDT','DOODUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOOD','bybit'),
	 ('NXPCUSDT@bybit','NXPCUSDT','NXPCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NXPC','bybit'),
	 ('HUMAUSDT@bybit','HUMAUSDT','HUMAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HUMA','bybit'),
	 ('ELDEUSDT@bybit','ELDEUSDT','ELDEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ELDE','bybit'),
	 ('AOUSDT@bybit','AOUSDT','AOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AO','bybit'),
	 ('AUSDT@bybit','AUSDT','AUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'A','bybit'),
	 ('ASRRUSDT@bybit','ASRRUSDT','ASRRUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ASRR','bybit'),
	 ('BDXNUSDT@bybit','BDXNUSDT','BDXNUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BDXN','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('LAUSDT@bybit','LAUSDT','LAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LA','bybit'),
	 ('CUDISUSDT@bybit','CUDISUSDT','CUDISUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CUDIS','bybit'),
	 ('RESOLVUSDT@bybit','RESOLVUSDT','RESOLVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RESOLV','bybit'),
	 ('SKATEUSDT@bybit','SKATEUSDT','SKATEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SKATE','bybit'),
	 ('ALGOUSDC@bybit','ALGOUSDC','ALGOUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ALGO','bybit'),
	 ('HBARUSDC@bybit','HBARUSDC','HBARUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HBAR','bybit'),
	 ('ENAUSDC@bybit','ENAUSDC','ENAUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENA','bybit'),
	 ('AAVEUSDC@bybit','AAVEUSDC','AAVEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AAVE','bybit'),
	 ('HOMEUSDT@bybit','HOMEUSDT','HOMEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HOME','bybit'),
	 ('JUPUSDC@bybit','JUPUSDC','JUPUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JUP','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('MOVEUSDC@bybit','MOVEUSDC','MOVEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MOVE','bybit'),
	 ('RENDERUSDC@bybit','RENDERUSDC','RENDERUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RENDER','bybit'),
	 ('CRVUSDC@bybit','CRVUSDC','CRVUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CRV','bybit'),
	 ('BOMBUSDT@bybit','BOMBUSDT','BOMBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BOMB','bybit'),
	 ('SPKUSDT@bybit','SPKUSDT','SPKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SPK','bybit'),
	 ('HUSDT@bybit','HUSDT','HUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'H','bybit'),
	 ('NEWTUSDT@bybit','NEWTUSDT','NEWTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NEWT','bybit'),
	 ('EIGENUSDC@bybit','EIGENUSDC','EIGENUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'EIGEN','bybit'),
	 ('POLUSDC@bybit','POLUSDC','POLUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'POL','bybit'),
	 ('BERAUSDC@bybit','BERAUSDC','BERAUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BERA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('GALAUSDC@bybit','GALAUSDC','GALAUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GALA','bybit'),
	 ('XOUSDT@bybit','XOUSDT','XOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XO','bybit'),
	 ('SAHARAUSDT@bybit','SAHARAUSDT','SAHARAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SAHARA','bybit'),
	 ('ICNTUSDT@bybit','ICNTUSDT','ICNTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ICNT','bybit'),
	 ('FRAGUSDT@bybit','FRAGUSDT','FRAGUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FRAG','bybit'),
	 ('NVDAXUSDT@bybit','NVDAXUSDT','NVDAXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NVDAX','bybit'),
	 ('COINXUSDT@bybit','COINXUSDT','COINXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'COINX','bybit'),
	 ('AIXBTUSDC@bybit','AIXBTUSDC','AIXBTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AIXBT','bybit'),
	 ('PENDLEUSDC@bybit','PENDLEUSDC','PENDLEUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PENDLE','bybit'),
	 ('ARUSDC@bybit','ARUSDC','ARUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AR','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('SUSDC@bybit','SUSDC','SUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'S','bybit'),
	 ('AAPLXUSDT@bybit','AAPLXUSDT','AAPLXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AAPLX','bybit'),
	 ('CRCLXUSDT@bybit','CRCLXUSDT','CRCLXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CRCLX','bybit'),
	 ('METAXUSDT@bybit','METAXUSDT','METAXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'METAX','bybit'),
	 ('HOODXUSDT@bybit','HOODXUSDT','HOODXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HOODX','bybit'),
	 ('AMZNXUSDT@bybit','AMZNXUSDT','AMZNXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AMZNX','bybit'),
	 ('GOOGLXUSDT@bybit','GOOGLXUSDT','GOOGLXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GOOGLX','bybit'),
	 ('STXUSDC@bybit','STXUSDC','STXUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'STX','bybit'),
	 ('ENSUSDC@bybit','ENSUSDC','ENSUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENS','bybit'),
	 ('ORDIUSDC@bybit','ORDIUSDC','ORDIUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ORDI','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PYTHUSDC@bybit','PYTHUSDC','PYTHUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PYTH','bybit'),
	 ('USD1USDT@bybit','USD1USDT','USD1USDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USD1','bybit'),
	 ('MNTUSD1@bybit','MNTUSD1','MNTUSD1@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MNT','bybit'),
	 ('MCDXUSDT@bybit','MCDXUSDT','MCDXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MCDX','bybit'),
	 ('TSLAXUSDT@bybit','TSLAXUSDT','TSLAXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TSLAX','bybit'),
	 ('HYPEUSDT@bybit','HYPEUSDT','HYPEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HYPE','bybit'),
	 ('JTOUSDC@bybit','JTOUSDC','JTOUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'JTO','bybit'),
	 ('DYDXUSDC@bybit','DYDXUSDC','DYDXUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DYDX','bybit'),
	 ('WUSDC@bybit','WUSDC','WUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'W','bybit'),
	 ('TACUSDT@bybit','TACUSDT','TACUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TAC','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('PUMPUSDT@bybit','PUMPUSDT','PUMPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PUMP','bybit'),
	 ('ERAUSDT@bybit','ERAUSDT','ERAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ERA','bybit'),
	 ('TAUSDT@bybit','TAUSDT','TAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TA','bybit'),
	 ('CATUSDT@bybit','CATUSDT','CATUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CAT','bybit'),
	 ('TREEUSDT@bybit','TREEUSDT','TREEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TREE','bybit'),
	 ('ICNTUSDC@bybit','ICNTUSDC','ICNTUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ICNT','bybit'),
	 ('TUNAUSDT@bybit','TUNAUSDT','TUNAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TUNA','bybit'),
	 ('TOWNSUSDT@bybit','TOWNSUSDT','TOWNSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TOWNS','bybit'),
	 ('TOWNSUSDC@bybit','TOWNSUSDC','TOWNSUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TOWNS','bybit'),
	 ('PROVEUSDT@bybit','PROVEUSDT','PROVEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PROVE','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('KUSDT@bybit','KUSDT','KUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'K','bybit'),
	 ('CAMPUSDT@bybit','CAMPUSDT','CAMPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CAMP','bybit'),
	 ('CFGUSDT@bybit','CFGUSDT','CFGUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CFG','bybit'),
	 ('SHARDSUSDT@bybit','SHARDSUSDT','SHARDSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SHARDS','bybit'),
	 ('WLFIUSDT@bybit','WLFIUSDT','WLFIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'WLFI','bybit'),
	 ('MNTUSDE@bybit','MNTUSDE','MNTUSDE@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MNT','bybit'),
	 ('ETHMNT@bybit','ETHMNT','ETHMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('SOMIUSDT@bybit','SOMIUSDT','SOMIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOMI','bybit'),
	 ('SOLMNT@bybit','SOLMNT','SOLMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit'),
	 ('XRPMNT@bybit','XRPMNT','XRPMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XRP','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('SKYUSDT@bybit','SKYUSDT','SKYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SKY','bybit'),
	 ('UUSDT@bybit','UUSDT','UUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'U','bybit'),
	 ('SUIMNT@bybit','SUIMNT','SUIMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUI','bybit'),
	 ('PEPEMNT@bybit','PEPEMNT','PEPEMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PEPE','bybit'),
	 ('HBARMNT@bybit','HBARMNT','HBARMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HBAR','bybit'),
	 ('DOGEMNT@bybit','DOGEMNT','DOGEMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGE','bybit'),
	 ('ADAMNT@bybit','ADAMNT','ADAMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ADA','bybit'),
	 ('AVNTUSDT@bybit','AVNTUSDT','AVNTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AVNT','bybit'),
	 ('ARTUSDT@bybit','ARTUSDT','ARTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ART','bybit'),
	 ('LINEAUSDT@bybit','LINEAUSDT','LINEAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LINEA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ENAMNT@bybit','ENAMNT','ENAMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENA','bybit'),
	 ('BBSOLMNT@bybit','BBSOLMNT','BBSOLMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BBSOL','bybit'),
	 ('LTCMNT@bybit','LTCMNT','LTCMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LTC','bybit'),
	 ('NXPCMNT@bybit','NXPCMNT','NXPCMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NXPC','bybit'),
	 ('TRUMPMNT@bybit','TRUMPMNT','TRUMPMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'TRUMP','bybit'),
	 ('XUSDUSDT@bybit','XUSDUSDT','XUSDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XUSD','bybit'),
	 ('HOLOUSDT@bybit','HOLOUSDT','HOLOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'HOLO','bybit'),
	 ('LAMNT@bybit','LAMNT','LAMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LA','bybit'),
	 ('VIRTUALMNT@bybit','VIRTUALMNT','VIRTUALMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VIRTUAL','bybit'),
	 ('PUMPMNT@bybit','PUMPMNT','PUMPMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PUMP','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ONDOMNT@bybit','ONDOMNT','ONDOMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ONDO','bybit'),
	 ('ERAMNT@bybit','ERAMNT','ERAMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ERA','bybit'),
	 ('APEXMNT@bybit','APEXMNT','APEXMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'APEX','bybit'),
	 ('HMNT@bybit','HMNT','HMNT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'H','bybit'),
	 ('ZKCUSDT@bybit','ZKCUSDT','ZKCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZKC','bybit'),
	 ('BTCXUSD@bybit','BTCXUSD','BTCXUSD@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('PORTALSUSDT@bybit','PORTALSUSDT','PORTALSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PORTALS','bybit'),
	 ('BARDUSDT@bybit','BARDUSDT','BARDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BARD','bybit'),
	 ('PUMPUSDC@bybit','PUMPUSDC','PUMPUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'PUMP','bybit'),
	 ('HUSDC@bybit','HUSDC','HUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'H','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('VIRTUALUSDC@bybit','VIRTUALUSDC','VIRTUALUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'VIRTUAL','bybit'),
	 ('SPXUSDC@bybit','SPXUSDC','SPXUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SPX','bybit'),
	 ('LBTCUSDT@bybit','LBTCUSDT','LBTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LBTC','bybit'),
	 ('ASTERUSDT@bybit','ASTERUSDT','ASTERUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ASTER','bybit'),
	 ('XPLUSDT@bybit','XPLUSDT','XPLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XPL','bybit'),
	 ('0GUSDT@bybit','0GUSDT','0GUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'0G','bybit'),
	 ('XANUSDT@bybit','XANUSDT','XANUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XAN','bybit'),
	 ('RLUSDUSDT@bybit','RLUSDUSDT','RLUSDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RLUSD','bybit'),
	 ('BTCRLUSD@bybit','BTCRLUSD','BTCRLUSD@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('MNTRLUSD@bybit','MNTRLUSD','MNTRLUSD@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MNT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('XRPRLUSD@bybit','XRPRLUSD','XRPRLUSD@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XRP','bybit'),
	 ('ETHRLUSD@bybit','ETHRLUSD','ETHRLUSD@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('FFUSDT@bybit','FFUSDT','FFUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FF','bybit'),
	 ('2ZUSDC@bybit','2ZUSDC','2ZUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'2Z','bybit'),
	 ('2ZUSDT@bybit','2ZUSDT','2ZUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'2Z','bybit'),
	 ('NOMUSDT@bybit','NOMUSDT','NOMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'NOM','bybit'),
	 ('ENSOUSDT@bybit','ENSOUSDT','ENSOUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENSO','bybit'),
	 ('YBUSDT@bybit','YBUSDT','YBUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'YB','bybit'),
	 ('RECALLUSDT@bybit','RECALLUSDT','RECALLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'RECALL','bybit'),
	 ('ZBTUSDT@bybit','ZBTUSDT','ZBTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZBT','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('METUSDT@bybit','METUSDT','METUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MET','bybit'),
	 ('METUSDC@bybit','METUSDC','METUSDC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MET','bybit'),
	 ('COMMONUSDT@bybit','COMMONUSDT','COMMONUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'COMMON','bybit'),
	 ('SYNDUSDT@bybit','SYNDUSDT','SYNDUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SYND','bybit'),
	 ('EATUSDT@bybit','EATUSDT','EATUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'EAT','bybit'),
	 ('MMTUSDT@bybit','MMTUSDT','MMTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MMT','bybit'),
	 ('LITKEYUSDT@bybit','LITKEYUSDT','LITKEYUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LITKEY','bybit'),
	 ('ENJUSDT@bybit','ENJUSDT','ENJUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ENJ','bybit'),
	 ('BTCUSDT@bybit','BTCUSDT','BTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BTC','bybit'),
	 ('ETHUSDT@bybit','ETHUSDT','ETHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('XRPUSDT@bybit','XRPUSDT','XRPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XRP','bybit'),
	 ('ETHBTC@bybit','ETHBTC','ETHBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETH','bybit'),
	 ('XRPBTC@bybit','XRPBTC','XRPBTC@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XRP','bybit'),
	 ('DOTUSDT@bybit','DOTUSDT','DOTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOT','bybit'),
	 ('XLMUSDT@bybit','XLMUSDT','XLMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XLM','bybit'),
	 ('LTCUSDT@bybit','LTCUSDT','LTCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LTC','bybit'),
	 ('DOGEUSDT@bybit','DOGEUSDT','DOGEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DOGE','bybit'),
	 ('CHZUSDT@bybit','CHZUSDT','CHZUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CHZ','bybit'),
	 ('AXSUSDT@bybit','AXSUSDT','AXSUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AXS','bybit'),
	 ('MANAUSDT@bybit','MANAUSDT','MANAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'MANA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('DYDXUSDT@bybit','DYDXUSDT','DYDXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'DYDX','bybit'),
	 ('COMPUSDT@bybit','COMPUSDT','COMPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'COMP','bybit'),
	 ('AAVEUSDT@bybit','AAVEUSDT','AAVEUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'AAVE','bybit'),
	 ('YFIUSDT@bybit','YFIUSDT','YFIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'YFI','bybit'),
	 ('LINKUSDT@bybit','LINKUSDT','LINKUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'LINK','bybit'),
	 ('SUSHIUSDT@bybit','SUSHIUSDT','SUSHIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SUSHI','bybit'),
	 ('UNIUSDT@bybit','UNIUSDT','UNIUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'UNI','bybit'),
	 ('KSMUSDT@bybit','KSMUSDT','KSMUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'KSM','bybit'),
	 ('ICPUSDT@bybit','ICPUSDT','ICPUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ICP','bybit'),
	 ('ADAUSDT@bybit','ADAUSDT','ADAUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ADA','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('ETCUSDT@bybit','ETCUSDT','ETCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ETC','bybit'),
	 ('XTZUSDT@bybit','XTZUSDT','XTZUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'XTZ','bybit'),
	 ('BCHUSDT@bybit','BCHUSDT','BCHUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BCH','bybit'),
	 ('QNTUSDT@bybit','QNTUSDT','QNTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'QNT','bybit'),
	 ('USDCUSDT@bybit','USDCUSDT','USDCUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'USDC','bybit'),
	 ('GRTUSDT@bybit','GRTUSDT','GRTUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'GRT','bybit'),
	 ('SOLUSDT@bybit','SOLUSDT','SOLUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'SOL','bybit'),
	 ('FILUSDT@bybit','FILUSDT','FILUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'FIL','bybit'),
	 ('BATUSDT@bybit','BATUSDT','BATUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'BAT','bybit'),
	 ('ZRXUSDT@bybit','ZRXUSDT','ZRXUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ZRX','bybit');
INSERT INTO tradevisor.tickers (ticker_code,ticker,figi,description,market_type,exchange,"precision",lot,"go",expiration,currency,provider) VALUES
	 ('CRVUSDT@bybit','CRVUSDT','CRVUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'CRV','bybit'),
	 ('ESUSDT@bybit','ESUSDT','ESUSDT@bybit','Trading',NULL,'bybit',1,1,NULL,NULL,'ES','bybit');

