plugins {
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyMgmtVersion}"
    id 'java'
    id 'jacoco'
}

dependencies {
    implementation project(':tinkoff-api')
    implementation project(':finam-api')
    testImplementation project(':tradevisor-db')

    implementation 'chat.giga:gigachat-java:0.1.7'
    implementation('io.netty:netty-all') {
        exclude group: 'io.netty', module: 'netty-transport-epoll'
    }
    implementation 'com.github.RussianInvestments:invest-api-java-sdk'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.telegram:telegrambots-meta:6.8.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.0.1'
    implementation 'commons-io:commons-io:2.11.0'
    implementation 'io.github.cdimascio:dotenv-java:2.3.2'
    implementation "org.jfree:jfreechart:1.5.4"

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.apache.httpcomponents.client5:httpclient5'
    implementation 'org.apache.commons:commons-lang3'

    implementation 'org.postgresql:postgresql'
    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'jakarta.annotation:jakarta.annotation-api'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.awaitility:awaitility'
    testImplementation 'org.liquibase:liquibase-core:4.26.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

task integrationTest(type: Test) {
    useJUnitPlatform {
        includeTags 'integration'
    }
    environment "TESTCONTAINERS_REUSE_ENABLE", "true"
    environment "TESTCONTAINERS_RYUK_DISABLED", "true"
    testLogging {
        events "passed", "skipped", "failed"
    }
}

bootJar.enabled = true
jar.enabled = false
