# ??????
javaVersion=21
springBootVersion=3.2.4
springCloudVersion=2023.0.1
springDependencyMgmtVersion=1.1.4

# ????? ???????????
lombokVersion=1.18.30
mapstructVersion=1.5.5.Final
jjwtVersion=0.12.3
postgresqlVersion=42.7.1
testcontainersVersion=1.19.7
liquibaseVersion=4.26.0
tinkoffInvestApiVersion=1.0.12

org.gradle.java.home=C:\\Users\\grebe\\.jdks\\ms-21.0.8