url=jdbc:postgresql://localhost:5432/{SPRING_DATASOURCE_DB_NAME:postgres}
changeLogFile=tradevisor-db/src/main/resources/changelog/changelog-master.yaml
username=${SPRING_DATASOURCE_USERNAME:postgres}
password=${SPRING_DATASOURCE_PASSWORD:password}
defaultSchemaName=tradevisor
liquibaseSchemaName=tradevisor
logLevel=INFO