url=jdbc:postgresql://localhost:5432/tradevisor
changeLogFile=tradevisor-db/src/main/resources/changelog/changelog-master.yaml
username=trvtrd
password=${SPRING_DATASOURCE_PASSWORD:password}
defaultSchemaName=tradevisor
liquibaseSchemaName=tradevisor
logLevel=INFO