server:
  port: 8080

logging:
  config: classpath:logback.xml
  level:
    ROOT: info
    org.jooq.Constants.org.jooq.Constants: WARN
    reactor.netty.http.client: INFO

management:
  server:
    port: 8002
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, db
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

spring:
  autoconfigure:
    exclude:
      - ru.ttech.piapi.springboot.configuration.InvestAutoConfiguration
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9411
    enabled: false #включать при работающем локально jaeger-клиенте
  application:
    name: tradevisor
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD_V2}
  liquibase:
    changeLog: classpath:changelog/changelog-master.yaml
    enabled: true
    url: jdbc:postgresql://postgres:5432/postgres
    user: postgres
    password: ${SPRING_DATASOURCE_PASSWORD_V2}

app:
  collect:                    # сбор информации для анализа
    events:                   # события, влияющие на ценную бумагу
      economic: true          # запрос у AI модельки про инструмент и экономический фон
      dividends: false        # получить точную дату выплаты дивидендов, если провайдер это предоставляет
      reports: false          # получить точную дату предоставления отчетности, если провайдер это предоставляет
      news: false             # получить новости последних дней, связанные с этим инструментом, если есть
    prices:
      delay: PT5M
      finam: true
      tinkoff: true
      bybit: true
      world: false
      init-tickers:
        delay: PT10M
  calculate:
    gap:
      enabled: false
      bars-required: 10
    fibo:
      enabled: true
      bars-required: 150
      min_touches_count:
        world: 3
        rus: 2
        crypto: 2
    tenx:
      enabled: true
      bars-required: 50
      look-back-bars: 30
      growth-factor: 5.0
      price-multiplier: 15.0
      stop-loss-multiplier: 10.0
    delay: PT10M
    batch-size: 1000
  trade:
    delay: PT1M
    risk-money:
      crypto: 1000
      rus: 1000000
      world: 1
    limits:  # риск в процентах от капитала на одну позицию
      crypto: 2
      rus: 0.1
      world: 0.1
    enabled: true
  chart:
    bars: 400
  notification:
    enabled: true
    delay: PT1M
  cleanup:
    cron: 0 0 0 1 * ?
    retention_days: 30
    enabled: true
  integration:
    cloudru:
      enabled: true
      key: ${CLOUDRU_API_KEY}
    proxyapi:
      enabled: false
      key: ${PROXY_API_KEY}
      url: https://api.proxyapi.ru/deepseek/chat/completions
    deepseek:
      enabled: false
      url: https://api.deepseek.com/v1/chat/completions
      key: ${DEEPSEEK_KEY}
    gigachat:
      enabled: false
      client-id: ${GIGACHAT_CLIENT_ID}
      client-secret: ${GIGACHAT_CLIENT_SECRET}
    telegram:
      enabled: false
      chat-id: ${CHAT_ID}
      chat-token: ${CHAT_TOKEN}
      base-url: ${BASE_URL}
      webhook-path: "/"
      re-register: false
      supergroup:
        chat-id: ${SUPERGROUP_CHAT_ID}
        positions-thread-id: ${POSITIONS_TOPIC_THREAD_ID}
        orders-thread-id: ${ORDERS_TOPIC_THREAD_ID}
        rus-thread-id: ${RUS_TOPIC_THREAD_ID}
        world-thread-id: ${WORLD_TOPIC_THREAD_ID}
        crypto-thread-id: ${CRYPTO_TOPIC_THREAD_ID}
        logs-thread-id: ${LOGS_TOPIC_THREAD_ID}
        statistics-thread-id: ${STATISTICS_TOPIC_THREAD_ID}
        errors-thread-id: ${ERRORS_TOPIC_THREAD_ID}
        events-thread-id: ${EVENTS_THREAD_ID}
    newsapi:
      enabled: false
      api-key: ${NEWS_API_KEY}
      url: "https://newsapi.org/v2/top-headlines?category=business"
      page-size: 50
    tinkoff:
      enabled: true
      token: ${TINKOFF_INVEST_TOKEN}
      host: "invest-public-api.tinkoff.ru:443"
      history-max-depth-days: 10
    finam:
      enabled: true
      secret: ${FINAM_API_KEY}
      url: https://api.finam.ru/v1
      host: api.finam.ru
      port: 443
      account-id: ${FINAM_ACCOUNT_KEY}
      history-max-depth-days: 10
      mt5-python-client-url: http://localhost:8001
      open-position-client: riskonly # mt5py для открытия через metatrader5, grpc для открытие через finam api, riskonly для сохранения параметров позиции в pg
    bybit:
      enabled: true
      key: ${BYBIT_KEY}
      secret: ${BYBIT_SECRET}
      url: https://api.bybit.com
      history-max-depth-days: 10