events {
    worker_connections 1024;
}

stream {
    upstream postgres_backend {
        server postgres:5432;
    }

    server {
        listen 5432;
        proxy_pass postgres_backend;
        proxy_timeout 10s;
        proxy_responses 1;
    }
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Подключение конфигурации сайта
    include /etc/nginx/conf.d/*.conf;
}