server:
  port: 8000

logging:
  config: config/logback.xml
  level:
    ROOT: debug
    org.jooq.Constants.org.jooq.Constants: WARN
    reactor.netty.http.client: INFO

management:
  server:
    port: 8000
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, db
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

spring:
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9411
    enabled: false #включать при работающем локально jaeger-клиенте
  application:
    name: tradevisor
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    changeLog: classpath:changelog/changelog-master.yaml
    enabled: true

app:
  collect:
    aiscore:
      cron: 1 * * * * *
    calendar:
      economic-event:
        enabled: true
        cron: 1 * * * * *
      dividends:
        enabled: true
        cron: 1 * * * * *
      expiration:
        enabled: true
        cron: 1 * * * * *
      holidays:
        enabled: true
        cron: 1 * * * * *
    news:
      enabled: true
      cron: 1 * * * * *
    prices:
      crypto:
        enabled: true
        cron: 1 * * * * *
      micex:
        enabled: true
        cron: 1 * * * * *
  calculate:
    strategy-one:
      cron: 1 * * * * *
      enabled: false
  trade:
    limits: 1
    enabled: false
  notification:
    enabled: true
    cron: 1 * * * * *
  integration:
    tinkoff:
      token: ${TINKOFF_INVEST_TOKEN}
      host: "invest-public-api.tinkoff.ru:443"
      history-max-depth-days: 1
    proxyapi:
      key: ${PROXY_API_KEY}
      url: https://api.proxyapi.ru/deepseek/chat/completions
    deepseek:
      url: https://api.deepseek.com/v1/chat/completions
      key: ${DEEPSEEK_KEY}
    gigachat:
      client-id: ${GIGACHAT_CLIENT_ID}
      client-secret: ${GIGACHAT_CLIENT_SECRET}
      url: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
    telegram:
      chat-id: ${CHAT_ID}
      chat-token: ${CHAT_TOKEN}
      base-url: ${BASE_URL}
    newsapi:
      api-key: ${NEWS_API_KEY}
      url: "https://newsapi.org/v2/top-headlines?category=business"
      page-size: 50