server:
  port: 8000

logging:
  config: config/logback.xml
  level:
    ROOT: debug
    org.jooq.Constants.org.jooq.Constants: WARN
    reactor.netty.http.client: INFO

management:
  server:
    port: 8000
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, db
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

spring:
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9411
    enabled: false #включать при работающем локально jaeger-клиенте
  application:
    name: tradevisor
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    changeLog: classpath:changelog/changelog-master.yaml
    enabled: true

app:
  collect:                    # сбор информации для анализа
    events:                   # события, влияющие на ценную бумагу
      cron: 1 * * * * *       # период сбора информации
      calendar:               # запланированные события в будущем
        economic: false       # макроэкономика и прочие
        reports: true         # отчеты эмитентов по стндартам
        dividends: true       # выплата дивидендов
        expiration: false     # экспирация
        holidays: false
      news:
        public: false
        ai: false
    forecast:
      cron: 1 * * * * *
      aiscore: false
      analysts: false
    prices:
      cron: 1 * * * * *
      crypto: false
      micex: false
  calculate:
    cron: 1 * * * * *
    strategy-one: false
  trade:
    limits: 1
    enabled: false
  notification:
    enabled: false
    cron: 1 * * * * *
  integration:
    tinkoff:
      enabled: true
      token: ${TINKOFF_INVEST_TOKEN}
      host: "invest-public-api.tinkoff.ru:443"
      history-max-depth-days: 1
    proxyapi:
      enabled: false
      key: ${PROXY_API_KEY}
      url: https://api.proxyapi.ru/deepseek/chat/completions
    deepseek:
      enabled: false
      url: https://api.deepseek.com/v1/chat/completions
      key: ${DEEPSEEK_KEY}
    gigachat:
      enabled: true
      client-id: ${GIGACHAT_CLIENT_ID}
      client-secret: ${GIGACHAT_CLIENT_SECRET}
    telegram:
      enabled: false
      chat-id: ${CHAT_ID}
      chat-token: ${CHAT_TOKEN}
      base-url: ${BASE_URL}
    newsapi:
      enabled: false
      api-key: ${NEWS_API_KEY}
      url: "https://newsapi.org/v2/top-headlines?category=business"
      page-size: 50