server:
  port: 8080

logging:
  config: classpath:logback.xml
  level:
    ROOT: info
    org.jooq.Constants.org.jooq.Constants: WARN
    reactor.netty.http.client: INFO

management:
  server:
    port: 8002
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, db
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

spring:
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9411
    enabled: false #включать при работающем локально jaeger-клиенте
  application:
    name: tradevisor
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    changeLog: classpath:changelog/changelog-master.yaml
    enabled: true

app:
  collect:                    # сбор информации для анализа
    ai-score:
      cron: 1 * * * * *
      enabled: false
    events:                   # события, влияющие на ценную бумагу
      cron: 1 * * * * *       # период сбора информации
      dividends: false        # выплата дивидендов
      economic: false         # макроэкономика и прочие
      expiration: false       # экспирация
      reports: false
      news: false
    prices:
      cron: 1 * * * * *
      finam: false
      tinkoff: false
      bybit: false
      yahoofinance: true
  calculate:
    cron: 1 * * * * *
    fibo: true
    bars_required_to_calculate_fibo: 300
    gap: false
    min_touches_count: 2
    batch-size: 1000
  trade:
    cron: 1 * * * * *
    limits: 1
    enabled: false
  notification:
    enabled: true
    cron: 1 * * * * *
  cleanup:
    cron: 0 0 0 1 * ?
    retention_days: 30
    enabled: true
  integration:
    proxyapi:
      enabled: false
      key: ${PROXY_API_KEY}
      url: https://api.proxyapi.ru/deepseek/chat/completions
    deepseek:
      enabled: false
      url: https://api.deepseek.com/v1/chat/completions
      key: ${DEEPSEEK_KEY}
    gigachat:
      enabled: false
      client-id: ${GIGACHAT_CLIENT_ID}
      client-secret: ${GIGACHAT_CLIENT_SECRET}
    telegram:
      enabled: true
      chat-id: ${CHAT_ID}
      chat-token: ${CHAT_TOKEN}
      base-url: ${BASE_URL}
      webhook-path: "/"
      re-register: false
    newsapi:
      enabled: false
      api-key: ${NEWS_API_KEY}
      url: "https://newsapi.org/v2/top-headlines?category=business"
      page-size: 50
    tinkoff:
      enabled: true
      token: ${TINKOFF_INVEST_TOKEN}
      host: "invest-public-api.tinkoff.ru:443"
      history-max-depth-days: 1
    finam:
      enabled: true
      secret: ${FINAM_API_KEY}
      url: https://api.finam.ru/v1
      host: api.finam.ru
      port: 443
      account-id: ${FINAM_ACCOUNT_KEY}
      history-max-depth-days: 30
    bybit:
      enabled: true
      key: ${BYBIT_KEY}
      secret: ${BYBIT_SECRET}
      url: https://api.bybit.com
      history-max-depth-days: 30
    yahoofinance:
      enabled: true
      url: https://query1.finance.yahoo.com
      history-max-depth-days: 7
